//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.ko", typeof(ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임 경로.
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임 옵션 변경.
        /// </summary>
        internal static string box_game_options {
            get {
                return ResourceManager.GetString("box_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 ID.
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 언어.
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 유니코드 기능 서포트 (필요).
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패쳐 경로.
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 패스워드.
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 웹사이트에서 부터 로그인하는게 피곤한가요?.
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 적용.
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 취소.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 취소중....
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 변경.
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 번역 다운로드.
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 닫기.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임 옵션.
        /// </summary>
        internal static string button_game_options {
            get {
                return ResourceManager.GetString("button_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 열기.
        /// </summary>
        internal static string button_open {
            get {
                return ResourceManager.GetString("button_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready To Play!.
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 일본어로 진행.
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 네, 리스크를 감수하고 패치하겠습니다.
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패쳐를 통해 로그인.
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 게임 클라이언트 폴더를 선택해주십시오..
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 새로운 패쳐 폴더를 지정해주십시오..
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 클라이언트 유니코드 패치가 &quot;{0}&quot;가 최신 업데이트된 클라이언트에 대해 변경이 되지 않았기에 적용이 되지 않았습니다. 클라이언트 패치가 비활성화되었습니다. 번역패치를 사용하실수 있지만, 몇몇 텍스트는 물음표로 표기될수도 있습니다. &quot;{0}&quot; 가 적용이 된후 클라이언트 유니코드 패치를 재시도해주세요..
        /// </summary>
        internal static string error_exe_patch_fail {
            get {
                return ResourceManager.GetString("error_exe_patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 현재 선택한 소울워커 서버는 .exe 파일의 변경을 지원하지 않습니다. 클라이언트 패치가 비활성화 되었습니다. 게임은 정상적으로 실행되지만, 텍스트 몇몇개가 미표기될수도 있습니다..
        /// </summary>
        internal static string error_exe_region_not_supported {
            get {
                return ResourceManager.GetString("error_exe_region_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 본인인증이 되지 않은 소울워커 계정입니다. 웹사이트에서 본인인증을 마쳐주세요..
        /// </summary>
        internal static string exception_account_not_validated {
            get {
                return ResourceManager.GetString("exception_account_not_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 탈퇴 신청이 완료되어 삭제될 예정입니다.
        ///만약 취소를 원하시는 경우 고객센터로 문의해주세요..
        /// </summary>
        internal static string exception_account_to_be_deleted {
            get {
                return ResourceManager.GetString("exception_account_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 이미 이 언어의 최신 번역이 업데이트되있습니다!.
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} 는 현재 작업중이라 닫을수 없습니다..
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 파일 경로가 존재하지 않습니다. &quot;{0}&quot; 가 없습니다. 파일 복구 불가능, 삭제합니다..
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그인에 캡챠가 필요하기에 패쳐로 로그인이 불가능합니다..
        /// </summary>
        internal static string exception_captcha_required {
            get {
                return ResourceManager.GetString("exception_captcha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그인 시도 횟수를 초과하였습니다. 한게임 JP 사이트에 로그인을해서 캡챠를 입력하셔야합니다..
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임 경로가 존재하지 않습니다 &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_not_exist {
            get {
                return ResourceManager.GetString("exception_directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임 폴더 &quot;{0}&quot; 경로에 권한설정을 실패하였습니다..
        /// </summary>
        internal static string exception_directory_rights {
            get {
                return ResourceManager.GetString("exception_directory_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID칸이 비어있습니다. 소울워커 ID를 입력하거나 패쳐에서 로그인하는 기능을 꺼주세요..
        /// </summary>
        internal static string exception_empty_id {
            get {
                return ResourceManager.GetString("exception_empty_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 비밀번호칸이 비어있습니다. 소울워커 비밀번호를 입력하거나 패쳐에서 로그인하는 기능을 꺼주세요..
        /// </summary>
        internal static string exception_empty_pw {
            get {
                return ResourceManager.GetString("exception_empty_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 지정된 폴더가 소울워커 게임 클라이언트 폴더가 아닙니다..
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 프로그램이 게임 파일내에 있습니다.
        ///게임 클라이언트에 오류및 오염을 일으킬수도 있습니다.
        ///다른 경로로 패쳐를 이동하거나 리스크름 감수하고 진행해주세요..
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그인중 오류가 발생했습니다. 웹페이지에 있는 설명에 따라주세요..
        /// </summary>
        internal static string exception_follow_instruction_webpage {
            get {
                return ResourceManager.GetString("exception_follow_instruction_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}가  이미 실행중이므로 진행이 불가능합니다..
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 {0} 프로그램이 감지되지 않습니다..
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커는 현재 점검중입니다..
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커가 최신버전으로 업데이트 되있지 않습니다. 업데이트 이후 다시 시도해주세요..
        /// </summary>
        internal static string exception_game_not_latest {
            get {
                return ResourceManager.GetString("exception_game_not_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 {0} 중입니다.
        ///점검시간: {1}
        ///오픈예정시간: {2}
        ///점검내용:
        ///{3}.
        /// </summary>
        internal static string exception_game_stove_maintenance {
            get {
                return ResourceManager.GetString("exception_game_stove_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}을 읽는데 실패했습니다..
        /// </summary>
        internal static string exception_generic_read_error {
            get {
                return ResourceManager.GetString("exception_generic_read_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 아이디 또는 비밀번호를 확인해주세요..
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그를 업로드하는데 실패하였습니다..
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그 파일이 존재하지 않습니다..
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 현재 선택한 소울워커 서버는 다이렉트 로그인을 지원하지 않습니다. 로그인 옵션이 비활성화 되었습니다..
        /// </summary>
        internal static string exception_login_option_not_supported {
            get {
                return ResourceManager.GetString("exception_login_option_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 다이렉트 로그인이 현재 활성화되있지 않습니다..
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 게임을 플레이하려면 이용약관에 먼저 동의하셔야합니다..
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 번역 버전을 읽는데 오류가 발생했습니다. 메뉴 -&gt; 강제 패치를 해주십시오..
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region &quot;{0}&quot; is unknown..
        /// </summary>
        internal static string exception_region_unknown {
            get {
                return ResourceManager.GetString("exception_region_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 인증 실패하였습니다..
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 관리자 권한이 필요하여 업데이트를 실패했습니다. 파일이 다른 곳에서 실행되고 있다던지...? 다시 시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_administrator_required {
            get {
                return ResourceManager.GetString("exception_rtpatch_administrator_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 오염된 패치 파일 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 오염된 파일 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패치 파일을 여는데 실패했습니다. 다시 시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_error_open_patch_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_error_open_patch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 드라이브에 공간이 부족해 업데이트에 실패했습니다..
        /// </summary>
        internal static string exception_rtpatch_insufficient_storage {
            get {
                return ResourceManager.GetString("exception_rtpatch_insufficient_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 파일이 존재하지 않습니다 &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 경로가 존재하지 않습니다. 게임 경로가 제대로 설정되어있는지 확인해주십시오..
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패치 파일을 여는데 실패했습니다. 다시 시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_open_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_open_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패치파일을 읽는데 실패하였습니다. 재시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_read_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_read_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 파일명을 수정하는데 실패했습니다. 재시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커를 업데이트중 발생미상의 오류가 발생하였습니다. 지금으로써 알려진 고치는 방법은 소울워커를 재인스톨 하는것 뿐입니다. 코드=[{0}]
        ///&quot;{1}&quot; 가 패쳐의 향상을 위해 업로드되었습니다..
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 파일 시간 설정에 실패했습니다. 다시 시도해주세요..
        /// </summary>
        internal static string exception_rtpatch_time_date_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_time_date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 혹은 한게임JP 서버가 연결을 차단하였습니다. (점검 스케줄을 체크해주세요).
        /// </summary>
        internal static string exception_server_refused_connection {
            get {
                return ResourceManager.GetString("exception_server_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 인증 실패하였습니다. IP/지정 나라가 차단되있는게 아닐지?.
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 강제 패치.
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} - ({1}) 의 새로운 번역.
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 언어:.
        /// </summary>
        internal static string form_language_pick {
            get {
                return ResourceManager.GetString("form_language_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 메뉴.
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소워 웹사이트 열기.
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 새로고침.
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gameforge.
        /// </summary>
        internal static string form_region_gf {
            get {
                return ResourceManager.GetString("form_region_gf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 일본 Gamecom.
        /// </summary>
        internal static string form_region_gjp {
            get {
                return ResourceManager.GetString("form_region_gjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 일본 Hange.
        /// </summary>
        internal static string form_region_jp {
            get {
                return ResourceManager.GetString("form_region_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japan Custom.
        /// </summary>
        internal static string form_region_jpc {
            get {
                return ResourceManager.GetString("form_region_jpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 한국.
        /// </summary>
        internal static string form_region_kr {
            get {
                return ResourceManager.GetString("form_region_kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 한국 Naver.
        /// </summary>
        internal static string form_region_nkr {
            get {
                return ResourceManager.GetString("form_region_nkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 지역:.
        /// </summary>
        internal static string form_region_pick {
            get {
                return ResourceManager.GetString("form_region_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 설정.
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 적용중....
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 다운로드중....
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 실행중....
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .exe 패치중....
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로딩 중....
        /// </summary>
        internal static string form_status_patch_load {
            get {
                return ResourceManager.GetString("form_status_patch_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패치 중....
        /// </summary>
        internal static string form_status_patch_patch {
            get {
                return ResourceManager.GetString("form_status_patch_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 저장 중....
        /// </summary>
        internal static string form_status_patch_save {
            get {
                return ResourceManager.GetString("form_status_patch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 준비중....
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 클라이언트 대기중....
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 클라이언트 중단대기중....
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pastebin으로 로그 업로드.
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows 일치.
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 번역파일이 최신이 아닌것을 확인, 강제 패치를 강행합니다..
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 몇몇 변경은 애플리케이션을 재시작한 이후에 적용됩니다..
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 더블클릭으로 복구....
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패쳐는 이제 여기에 숨겨집니다..
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커 패쳐.
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This program comes with ABSOLUTELY NO WARRANTY
        ///This is free software, and you are welcome to redistribute it under certain conditions.
        ///
        ///소울워커 패쳐는 최신의 번역 파일들을 소울워커 클라이언트에 오류 없이 깨끗하게 업데이트 하기 위해 만들어진 프로그램 입니다.
        ///또한, SWHQ 번역팀(한국번역은 소울워커 카페 번역팀)에 의해 번역이 된 최신번역 파일들을 손쉽게 다운로드하고 적용시킬수 있습니다..
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 백엄 파일 확인. 클라이언트에 이 파일을을 복구시키겠습니까?
        ///현재 클라이언트에 있는 파일들은 {0} 번역으로 교체됩니다.
        ///아니요를 선택하시면 백업 파일들이 삭제됩니다..
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 프로그램이 게임 파일내에 있습니다.
        ///게임 클라이언트에 오류및 오염을 일으킬수도 있습니다.
        ///정말 이 폴더로 지정하겠습니까?.
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 로그파일이 &quot;{0}&quot; 로 업로드되었습니다.
        ///링크가 클립보드로 복사되었습니다..
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 계정.
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 소울워커.
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 패쳐.
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
