//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Расположение игры.
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Изменить настройки игры.
        /// </summary>
        internal static string box_game_options {
            get {
                return ResourceManager.GetString("box_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker ID.
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Язык.
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Пропатчить .exe для поддержки других юникод языков.
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Расположение патчера.
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker пароль.
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Устали входить с сайта?.
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Применить.
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Отмена.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Отменяется....
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Изменить.
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Загрузить перевод.
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Выйти.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Настройки игры.
        /// </summary>
        internal static string button_game_options {
            get {
                return ResourceManager.GetString("button_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Открыть.
        /// </summary>
        internal static string button_open {
            get {
                return ResourceManager.GetString("button_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Готов играть!.
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Начать игру Raw.
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Да, я знаю о рисках и хочу это пропатчить.
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Авторизация при помощи патчера.
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Выберите папку с игровым клиентом Soulworker..
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Выберите новую папку для патчера..
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .exe патч не был применен из-за  &quot;{0} &quot; не был обновлен для нового клиента после последнего обновления. Клиентское исправление было отключено. Игра все еще может работать, за исключением некоторых текстов не будет показано. Повторите попытку позже, когда реализуется  &quot;{0} &quot;..
        /// </summary>
        internal static string error_exe_patch_fail {
            get {
                return ResourceManager.GetString("error_exe_patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ваш регион Soulworker не поддерживает исправления .exe. Клиентский патч отключен. Игра все еще может работать, за исключением некоторых текстов, которые не будут показаны..
        /// </summary>
        internal static string error_exe_region_not_supported {
            get {
                return ResourceManager.GetString("error_exe_region_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ваша учетная запись soulworker не подтверждена. Пожалуйста, подтвердите свой аккаунт на сайте..
        /// </summary>
        internal static string exception_account_not_validated {
            get {
                return ResourceManager.GetString("exception_account_not_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Эта учетная запись ожидает удаления, если вы хотите отменить это, обратитесь в службу поддержки..
        /// </summary>
        internal static string exception_account_to_be_deleted {
            get {
                return ResourceManager.GetString("exception_account_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a У вас уже есть последние ({0} JST) файлы перевода для этого языка!.
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} сейчас занят и не может быть закрыт..
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Каталог с файлом &quot;{0}&quot; не существует. Невозможно восстановить эту папку, и она будет удалена..
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не возможно авторизоваться с помощью патчера, требуется ввод кпчи..
        /// </summary>
        internal static string exception_captcha_required {
            get {
                return ResourceManager.GetString("exception_captcha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Слишком много неправильных входов.. Вы должны войти в систему и заполнить капчу на сайте Hange..
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Папка игры не существует &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_not_exist {
            get {
                return ResourceManager.GetString("exception_directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Невозможно установить правильные разрешения для папки с игрой &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_rights {
            get {
                return ResourceManager.GetString("exception_directory_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Идентификатор не может быть пустым, пожалуйста, настройте свой идентификатор Soulworker ID или снимите флажок для входа в систему..
        /// </summary>
        internal static string exception_empty_id {
            get {
                return ResourceManager.GetString("exception_empty_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Пароль не может быть пустым, установите пароль Soulworker или снимите флажок для входа..
        /// </summary>
        internal static string exception_empty_pw {
            get {
                return ResourceManager.GetString("exception_empty_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Выбранная папка не является папкой игрового клиента Soulworker..
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Программа находится в той же или в подпапке, что и ваш игровой клиент..
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a При входе в систему произошла ошибка, следуйте инструкциям на веб-странице..
        /// </summary>
        internal static string exception_follow_instruction_webpage {
            get {
                return ResourceManager.GetString("exception_follow_instruction_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удается продолжить, так как {0} уже запущен..
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Установленный Soulworker {0} не найден..
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker сейчас на тех. обслуживании..
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker не обновлty до последней версии. Повторите попытку после обновления soulworker..
        /// </summary>
        internal static string exception_game_not_latest {
            get {
                return ResourceManager.GetString("exception_game_not_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Обслуживание Soulworker {0}
        ///{1}
        ///Обслуживание заканчивается на {2}.
        ///Контрольный список:
        ///{3}.
        /// </summary>
        internal static string exception_game_stove_maintenance {
            get {
                return ResourceManager.GetString("exception_game_stove_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось прочитать {0}..
        /// </summary>
        internal static string exception_generic_read_error {
            get {
                return ResourceManager.GetString("exception_generic_read_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Неверный ID или пароль..
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось отправить файл логов..
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Файл с логами не существует..
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ваш регион Soulworker не поддерживает прямой вход. Опция входа была отключена..
        /// </summary>
        internal static string exception_login_option_not_supported {
            get {
                return ResourceManager.GetString("exception_login_option_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Опция прямого входа не активна..
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Чтобы играть в игру, вы должны принять Условия использования..
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ошибка чтения версии перевода, попробуйте Меню -&gt; Принудительное исправление.
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Регион &quot;{0}&quot; не известен..
        /// </summary>
        internal static string exception_region_unknown {
            get {
                return ResourceManager.GetString("exception_region_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Проверка не удалась..
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось обновить, поскольку для файла требуются права администратора. Возможно файл уже используется? Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_administrator_required {
            get {
                return ResourceManager.GetString("exception_rtpatch_administrator_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Поврежденный файл патча &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Файл поврежден &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ошибка при открытии файла патча. Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_error_open_patch_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_error_open_patch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось обновить, т.к. на диске недостаточно свободного места..
        /// </summary>
        internal static string exception_rtpatch_insufficient_storage {
            get {
                return ResourceManager.GetString("exception_rtpatch_insufficient_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Файл не существует &quot;{0}&quot;.
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Каталог не существует, убедитесь, что каталог игры установлен правильно..
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось открыть файл патча. Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_open_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_open_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось прочитать файл исправления. Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_read_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_read_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось переименовать файл. Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Произошла неизвестная ошибка при обновлении Soulworker. Самый известный способ исправить это полная переустановка Soulworker. Код = [{0}].
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Не удалось установить метку времени / даты файла. Попробуйте снова..
        /// </summary>
        internal static string exception_rtpatch_time_date_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_time_date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Сервер отказал в соединении. (Обслуживание сервера?).
        /// </summary>
        internal static string exception_server_refused_connection {
            get {
                return ResourceManager.GetString("exception_server_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Проверка не удалась. Может быть, ваш IP / регион заблокирован?.
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a О нас.
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Принудительный патч.
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Новый перевод для {0} - ({1}).
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Язык:.
        /// </summary>
        internal static string form_language_pick {
            get {
                return ResourceManager.GetString("form_language_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Меню.
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Открыть SW веб сайт.
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Обновить.
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gameforge.
        /// </summary>
        internal static string form_region_gf {
            get {
                return ResourceManager.GetString("form_region_gf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Япония Gamecom.
        /// </summary>
        internal static string form_region_gjp {
            get {
                return ResourceManager.GetString("form_region_gjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Япония Hange.
        /// </summary>
        internal static string form_region_jp {
            get {
                return ResourceManager.GetString("form_region_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japan Custom.
        /// </summary>
        internal static string form_region_jpc {
            get {
                return ResourceManager.GetString("form_region_jpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Корея.
        /// </summary>
        internal static string form_region_kr {
            get {
                return ResourceManager.GetString("form_region_kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Корея Naver.
        /// </summary>
        internal static string form_region_nkr {
            get {
                return ResourceManager.GetString("form_region_nkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Регион:.
        /// </summary>
        internal static string form_region_pick {
            get {
                return ResourceManager.GetString("form_region_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Настройки.
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Применяется....
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Загружается....
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Обработка....
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Пропатчивание .exe....
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Загрузка....
        /// </summary>
        internal static string form_status_patch_load {
            get {
                return ResourceManager.GetString("form_status_patch_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Пропатчивание....
        /// </summary>
        internal static string form_status_patch_patch {
            get {
                return ResourceManager.GetString("form_status_patch_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Сохранение....
        /// </summary>
        internal static string form_status_patch_save {
            get {
                return ResourceManager.GetString("form_status_patch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Подготовка....
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ожидание игры....
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ожидание завершения игры....
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Загрузить логи в Pastebin.
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Как в Windows.
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Устаревшие файлы перевода, сейчас начнется принудительное исправление..
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Некоторые изменения будут применены только после перезапуска приложения..
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Нажмите дважды, что бы восстоновить....
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Патчер был свернут в панель уведомлений.
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker Патчер.
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Эта программа поставляется без КАКИХ-ЛИБО ГАРАНТИЙ.
        ///
        ///Это бесплатное программное обеспечение, и вы можете распространять его при определенных условиях.
        ///
        ///Soulworker Patcher был сделан, чтобы легко исправлять последние переводы вашему клиенту Soulworker без особого риска повреждения ваших исходных файлов при обновлении.
        ///Он также может загружать последние переводы из команды перевода SWHQ и применять их в любое время..
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Найдены резервные копии файлов. Вы хотите восстановить их в своем клиенте?
        ///Существующие из вашего клиента будут заменены на перевод {0}.
        ///Выбор Нет приведет к удалению этих файлов резервных копий..
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Программа находится в той же или в подпапке, что и ваш игровой клиент..
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Лог был загружен в: &quot;{0}&quot;.
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Учетные данные.
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker.
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Патчер.
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
