//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWPatcher.Resources.vi", typeof(vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đường dẫn của game.
        /// </summary>
        internal static string box_game_dir {
            get {
                return ResourceManager.GetString("box_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thay đổi tùy chỉnh trong game.
        /// </summary>
        internal static string box_game_options {
            get {
                return ResourceManager.GetString("box_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker ID.
        /// </summary>
        internal static string box_id {
            get {
                return ResourceManager.GetString("box_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ngôn ngữ.
        /// </summary>
        internal static string box_language {
            get {
                return ResourceManager.GetString("box_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chỉnh sửa .exe để hỗ trợ ký tự Unicode.
        /// </summary>
        internal static string box_patch_exe {
            get {
                return ResourceManager.GetString("box_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đường dẫn Patcher.
        /// </summary>
        internal static string box_patcher_dir {
            get {
                return ResourceManager.GetString("box_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker Password.
        /// </summary>
        internal static string box_pw {
            get {
                return ResourceManager.GetString("box_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ngán ngẩm phải đăng nhập từ website?.
        /// </summary>
        internal static string box_want_login {
            get {
                return ResourceManager.GetString("box_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áp dụng.
        /// </summary>
        internal static string button_apply {
            get {
                return ResourceManager.GetString("button_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hủy bỏ.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang hủy bỏ....
        /// </summary>
        internal static string button_cancelling {
            get {
                return ResourceManager.GetString("button_cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thay đổi.
        /// </summary>
        internal static string button_change {
            get {
                return ResourceManager.GetString("button_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tải bản dịch.
        /// </summary>
        internal static string button_download_translation {
            get {
                return ResourceManager.GetString("button_download_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thoát.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tùy chỉnh trò chơi.
        /// </summary>
        internal static string button_game_options {
            get {
                return ResourceManager.GetString("button_game_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mở.
        /// </summary>
        internal static string button_open {
            get {
                return ResourceManager.GetString("button_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready To Play!.
        /// </summary>
        internal static string button_play {
            get {
                return ResourceManager.GetString("button_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bắt đầu trò chơi mà không dùng Patch.
        /// </summary>
        internal static string button_play_raw {
            get {
                return ResourceManager.GetString("button_play_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tôi đồng ý với rủi ro và đồng ý chỉnh sửa..
        /// </summary>
        internal static string check_patch_exe {
            get {
                return ResourceManager.GetString("check_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đăng nhập bằng Patcher.
        /// </summary>
        internal static string check_want_login {
            get {
                return ResourceManager.GetString("check_want_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chọn đến thư mục game..
        /// </summary>
        internal static string dialog_folder_change_game_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_game_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chọn đến thư mục mà Patcher làm việc..
        /// </summary>
        internal static string dialog_folder_change_patcher_dir {
            get {
                return ResourceManager.GetString("dialog_folder_change_patcher_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Không thể patch tập tin .exe vì lý do phương thức &quot;{0}&quot; chưa được cập nhật cho client hiện tại. Patch cho client đã bị vô hiệu hóa. Client vẫn sẽ được cập nhật, ngoại trừ việc một vài đoạn chữ sẽ không hiện. Xin vui lòng thử lại sau khi &quot;{0}&quot; đã được hoàn thiện..
        /// </summary>
        internal static string error_exe_patch_fail {
            get {
                return ResourceManager.GetString("error_exe_patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker dành cho khu vực được chọn không hỗ trợ patch tập tin .exe. Patch đã bị bỏ qua. Trò chơi vẫn sẽ hoạt động ngoại trừ một số chữ có thể sẽ không hiển thị được..
        /// </summary>
        internal static string error_exe_region_not_supported {
            get {
                return ResourceManager.GetString("error_exe_region_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tài khoản chưa được kích hoạt. Xin vui lòng kích hoạt tài khoản..
        /// </summary>
        internal static string exception_account_not_validated {
            get {
                return ResourceManager.GetString("exception_account_not_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tài khoản này đang trong giai đoạn &quot;Đang xóa&quot;, nếu như bạn muốn hủy bỏ hành động này, xin vui lòng liên hệ &quot;Chăm sóc khách hàng&quot;.
        /// </summary>
        internal static string exception_account_to_be_deleted {
            get {
                return ResourceManager.GetString("exception_account_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bạn đã có phiên bản mới nhất ({0} JST) của bản dịch này!.
        /// </summary>
        internal static string exception_already_latest_translation {
            get {
                return ResourceManager.GetString("exception_already_latest_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} đang bận và không thể thoát..
        /// </summary>
        internal static string exception_cannot_close {
            get {
                return ResourceManager.GetString("exception_cannot_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thư mục bao gồm tập tin &quot;{0}&quot; không tồn tại. Không thể khôi phục, thư mục sẽ bị xóa..
        /// </summary>
        internal static string exception_cannot_restore_file {
            get {
                return ResourceManager.GetString("exception_cannot_restore_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Không thể đăng nhập bằng patcher vì lượt đăng nhập của bạn đòi hỏi phải điền captcha.
        /// </summary>
        internal static string exception_captcha_required {
            get {
                return ResourceManager.GetString("exception_captcha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đăng nhập thất bại quá nhiều. Xin vui lòng đăng nhập và hoàn tất captcha tại trang chủ của Hange..
        /// </summary>
        internal static string exception_captcha_validation {
            get {
                return ResourceManager.GetString("exception_captcha_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thư mục game không tồn tại &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_not_exist {
            get {
                return ResourceManager.GetString("exception_directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Không thể truy cập vào thư mục &quot;{0}&quot;..
        /// </summary>
        internal static string exception_directory_rights {
            get {
                return ResourceManager.GetString("exception_directory_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID không được để trống, xin vui lòng nhập ID hoặc bỏ chọn &quot;Đăng nhập bằng Patcher&quot;.
        /// </summary>
        internal static string exception_empty_id {
            get {
                return ResourceManager.GetString("exception_empty_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password không được để trống, xin vui lòng nhập Password hoặc bỏ chọn &quot;Đăng nhập bằng Patcher&quot;.
        /// </summary>
        internal static string exception_empty_pw {
            get {
                return ResourceManager.GetString("exception_empty_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected folder is not a Soulworker game client folder..
        /// </summary>
        internal static string exception_folder_not_game_folder {
            get {
                return ResourceManager.GetString("exception_folder_not_game_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thư mục hoạt động của Patcher đang ở trong thư mục của game.
        ///Điều này có thể gây ra xung đột hoặc hỏng hóc tệp tin của game.
        ///Xin vui lòng di chuyển thư mục đến địa điểm khác hoặc chấp nhận rủi ro và tiếp tục dùng..
        /// </summary>
        internal static string exception_folder_same_path_game {
            get {
                return ResourceManager.GetString("exception_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Có lỗi xảy kha trong lúc đăng nhập, xin vui lòng làm theo hướng dẫn trên trang web..
        /// </summary>
        internal static string exception_follow_instruction_webpage {
            get {
                return ResourceManager.GetString("exception_follow_instruction_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Không thể tiếp tục vì {0} đang chạy..
        /// </summary>
        internal static string exception_game_already_open {
            get {
                return ResourceManager.GetString("exception_game_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Không tìm thấy Soulworker {0}..
        /// </summary>
        internal static string exception_game_install_not_found {
            get {
                return ResourceManager.GetString("exception_game_install_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máy chủ Soulworker đang trong bảo trì..
        /// </summary>
        internal static string exception_game_maintenance {
            get {
                return ResourceManager.GetString("exception_game_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker chưa được cập nhật đến phiên bản mới nhất. Xin vui lòng thử lại sau khi cập nhật Soulworker..
        /// </summary>
        internal static string exception_game_not_latest {
            get {
                return ResourceManager.GetString("exception_game_not_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker hiện đang trong bảo trì {0}
        ///Thời gian: {1}
        ///Bảo trì sẽ kết thúc vào lúc {2}.
        ///Danh sách đối chiếu:
        ///{3}.
        /// </summary>
        internal static string exception_game_stove_maintenance {
            get {
                return ResourceManager.GetString("exception_game_stove_maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đọc {0} thất bại..
        /// </summary>
        internal static string exception_generic_read_error {
            get {
                return ResourceManager.GetString("exception_generic_read_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sai ID hoặc mật khẩu..
        /// </summary>
        internal static string exception_incorrect_id_pw {
            get {
                return ResourceManager.GetString("exception_incorrect_id_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đăng tệp log thất bại..
        /// </summary>
        internal static string exception_log_file_failed {
            get {
                return ResourceManager.GetString("exception_log_file_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tệp Log không tồn tại..
        /// </summary>
        internal static string exception_log_not_exist {
            get {
                return ResourceManager.GetString("exception_log_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker dành cho khu vực được chọn hiện không hỗ trợ chức năng đăng nhập bằng SWPatcher. Tùy chọn đăng nhập bằng SWPatcher đã sẽ bị bỏ..
        /// </summary>
        internal static string exception_login_option_not_supported {
            get {
                return ResourceManager.GetString("exception_login_option_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đăng nhập bằng Patcher không được sử dụng..
        /// </summary>
        internal static string exception_not_login_option {
            get {
                return ResourceManager.GetString("exception_not_login_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Để tham gia trò chơi, bạn phải đồng ý Điều khoản dịch vụ..
        /// </summary>
        internal static string exception_not_tos {
            get {
                return ResourceManager.GetString("exception_not_tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Có lỗi khi đọc phiên bản của bản dịch, xin vui lòng nhấn thử Menu -&gt; Làm lại Patch mới.
        /// </summary>
        internal static string exception_read_translation_ini {
            get {
                return ResourceManager.GetString("exception_read_translation_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region &quot;{0}&quot; is unknown..
        /// </summary>
        internal static string exception_region_unknown {
            get {
                return ResourceManager.GetString("exception_region_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kiểm tra thất bại..
        /// </summary>
        internal static string exception_retry_validation_failed {
            get {
                return ResourceManager.GetString("exception_retry_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cập nhật tập tin tất bại vì thiếu quyền truy cập hoặc tập tin đang được sử dụng. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_administrator_required {
            get {
                return ResourceManager.GetString("exception_rtpatch_administrator_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tập tin patch &quot;{0}&quot; đã bị hỏng.
        /// </summary>
        internal static string exception_rtpatch_corrupt {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tập tin &quot;{0}&quot; đã bị hỏng.
        /// </summary>
        internal static string exception_rtpatch_corrupt_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_corrupt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Có lỗi xảy ra khi mở tập tin patch. Vui lòng thử lại sau..
        /// </summary>
        internal static string exception_rtpatch_error_open_patch_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_error_open_patch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cập nhật thất bại vì thiếu không gian trống trên ổ đĩa..
        /// </summary>
        internal static string exception_rtpatch_insufficient_storage {
            get {
                return ResourceManager.GetString("exception_rtpatch_insufficient_storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tập tin &quot;{0}&quot; không tồn tại.
        /// </summary>
        internal static string exception_rtpatch_missing_file {
            get {
                return ResourceManager.GetString("exception_rtpatch_missing_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thư mục không tồn tại, xin vui lòng kiểm tra lại đường dẫn.
        /// </summary>
        internal static string exception_rtpatch_not_exist_directory {
            get {
                return ResourceManager.GetString("exception_rtpatch_not_exist_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mở tập tin patch thất bại. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_open_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_open_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đọc tập tin patch thất bại. Vui lòng thử lại sau..
        /// </summary>
        internal static string exception_rtpatch_read_patch_file_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_read_patch_file_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đổi tên tập tin thất bại, xin hãy thử lại.
        /// </summary>
        internal static string exception_rtpatch_rename_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_rename_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Có lỗi xảy ra trong lúc cập nhật SoulWorker, cách tốt nhất là cài đặt lại trò chơi. Code=[{0}]
        ///&quot;{1}&quot; đã được đăng lên để cải thiện patcher..
        /// </summary>
        internal static string exception_rtpatch_result {
            get {
                return ResourceManager.GetString("exception_rtpatch_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đặt mốc thời gian cho tập tin thất bại. Xin vui lòng thử lại..
        /// </summary>
        internal static string exception_rtpatch_time_date_fail {
            get {
                return ResourceManager.GetString("exception_rtpatch_time_date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máy chủ SoulWorker từ chối kết nối (bảo trì ???).
        /// </summary>
        internal static string exception_server_refused_connection {
            get {
                return ResourceManager.GetString("exception_server_refused_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kiểm tra thất bại. Bạn có chắc rằng bạn không bị chặn?.
        /// </summary>
        internal static string exception_validation_failed {
            get {
                return ResourceManager.GetString("exception_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thông tin.
        /// </summary>
        internal static string form_about {
            get {
                return ResourceManager.GetString("form_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Làm lại Patch mới.
        /// </summary>
        internal static string form_force_patch {
            get {
                return ResourceManager.GetString("form_force_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Có bản dịch mới cho {0} - ({1}).
        /// </summary>
        internal static string form_label_new_translation {
            get {
                return ResourceManager.GetString("form_label_new_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ngôn ngữ:.
        /// </summary>
        internal static string form_language_pick {
            get {
                return ResourceManager.GetString("form_language_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        internal static string form_menu {
            get {
                return ResourceManager.GetString("form_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mở trang chủ SW.
        /// </summary>
        internal static string form_open_sw_webpage {
            get {
                return ResourceManager.GetString("form_open_sw_webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        internal static string form_refresh {
            get {
                return ResourceManager.GetString("form_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gameforge.
        /// </summary>
        internal static string form_region_gf {
            get {
                return ResourceManager.GetString("form_region_gf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nhật Bản Gamecom.
        /// </summary>
        internal static string form_region_gjp {
            get {
                return ResourceManager.GetString("form_region_gjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nhật Bản Hange.
        /// </summary>
        internal static string form_region_jp {
            get {
                return ResourceManager.GetString("form_region_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japanese Custom.
        /// </summary>
        internal static string form_region_jpc {
            get {
                return ResourceManager.GetString("form_region_jpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hàn Quốc.
        /// </summary>
        internal static string form_region_kr {
            get {
                return ResourceManager.GetString("form_region_kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hàn Quốc Naver.
        /// </summary>
        internal static string form_region_nkr {
            get {
                return ResourceManager.GetString("form_region_nkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Khu vực:.
        /// </summary>
        internal static string form_region_pick {
            get {
                return ResourceManager.GetString("form_region_pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cài đặt.
        /// </summary>
        internal static string form_settings {
            get {
                return ResourceManager.GetString("form_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang áp dụng....
        /// </summary>
        internal static string form_status_apply {
            get {
                return ResourceManager.GetString("form_status_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang tải....
        /// </summary>
        internal static string form_status_download {
            get {
                return ResourceManager.GetString("form_status_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_idle {
            get {
                return ResourceManager.GetString("form_status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang làm việc....
        /// </summary>
        internal static string form_status_patch {
            get {
                return ResourceManager.GetString("form_status_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patching .exe....
        /// </summary>
        internal static string form_status_patch_exe {
            get {
                return ResourceManager.GetString("form_status_patch_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading.....
        /// </summary>
        internal static string form_status_patch_load {
            get {
                return ResourceManager.GetString("form_status_patch_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang cập nhật.....
        /// </summary>
        internal static string form_status_patch_patch {
            get {
                return ResourceManager.GetString("form_status_patch_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang lưu lại.....
        /// </summary>
        internal static string form_status_patch_save {
            get {
                return ResourceManager.GetString("form_status_patch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang chuẩn bị....
        /// </summary>
        internal static string form_status_prepare {
            get {
                return ResourceManager.GetString("form_status_prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string form_status_update_client {
            get {
                return ResourceManager.GetString("form_status_update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang chờ khởi động game....
        /// </summary>
        internal static string form_status_wait_client {
            get {
                return ResourceManager.GetString("form_status_wait_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đang chời thoát game....
        /// </summary>
        internal static string form_status_wait_close {
            get {
                return ResourceManager.GetString("form_status_wait_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Đăng tệp Log lên Pastebin.
        /// </summary>
        internal static string form_upload_log {
            get {
                return ResourceManager.GetString("form_upload_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tự động.
        /// </summary>
        internal static string match_windows {
            get {
                return ResourceManager.GetString("match_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bản dịch lỗi thời, tiến hành làm lại Patch mới..
        /// </summary>
        internal static string notice_outdated_translation {
            get {
                return ResourceManager.GetString("notice_outdated_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Một vài thay đổi sẽ được áp dụng sau khi khởi động lại chương trình..
        /// </summary>
        internal static string notice_pending_restart {
            get {
                return ResourceManager.GetString("notice_pending_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double click để hiện....
        /// </summary>
        internal static string notify_balloon_text {
            get {
                return ResourceManager.GetString("notify_balloon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patcher ẩn ở đây.
        /// </summary>
        internal static string notify_balloon_title {
            get {
                return ResourceManager.GetString("notify_balloon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker Patcher.
        /// </summary>
        internal static string notify_text {
            get {
                return ResourceManager.GetString("notify_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This program comes with ABSOLUTELY NO WARRANTY
        ///This is free software, and you are welcome to redistribute it under certain conditions.
        ///
        ///Soulworker Patcher được làm ra là để áp dụng các bản dịch vào game mà không gây ra nhiều rủi ro hỏng tệp của game.
        ///Nguồn dịch được tải từ nhóm dịch ở SWHQ..
        /// </summary>
        internal static string patcher_description {
            get {
                return ResourceManager.GetString("patcher_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tìm thấy Backup. Bạn có muốn khôi phục backup về thư mục game không?
        ///Tệp đang tồn tại ở thư mục game sẽ bị hoán đổi với bản dịch {0}.
        ///Chọn No sẽ tiến hành xóa backup..
        /// </summary>
        internal static string question_backup_files_found {
            get {
                return ResourceManager.GetString("question_backup_files_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Điểm đến đang ở trong thư mục của game.
        ///Điều này có thể gây ra xung đột hoặc hỏng hóc tệp tin của game.
        ///Bạn có chắc rằng bạn muốn chọn thư mục này?.
        /// </summary>
        internal static string question_folder_same_path_game {
            get {
                return ResourceManager.GetString("question_folder_same_path_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tệp Log đã được đăng &quot;{0}&quot;
        ///Đường link đã được copy vào clipboard..
        /// </summary>
        internal static string success_log_file_upload {
            get {
                return ResourceManager.GetString("success_log_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thông tin đăng nhập.
        /// </summary>
        internal static string tab_credentials {
            get {
                return ResourceManager.GetString("tab_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soulworker.
        /// </summary>
        internal static string tab_game {
            get {
                return ResourceManager.GetString("tab_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patcher.
        /// </summary>
        internal static string tab_patcher {
            get {
                return ResourceManager.GetString("tab_patcher", resourceCulture);
            }
        }
    }
}
